  {
    name: "Aviões",
    items: [
      { title: "Aiaa DBF 13", sub: "Asa voadora",
        img: "13f28WJ-PC0NYvo9DKdJTaYRZZJRKDuwO", zip: "18HdrEGp5mjfShpnwNwGjtFPQZxqP5j7R" },
      { title: "ASK14 - Plane", sub: "Planador",
        img: "1ygWlmWmEeREZGohOwKHlCy0yzcW-R5GQ", zip: "1NNrs3sdp5rZWQOmc5I0Ep2oKT2jFM_Uo" },
      { title: "Avião 787", sub: "Boeing 787",
        img: "1tnATti5QdjJFx-BFUUQglF7e6W09Xdl3", zip: "1z4jhSqPA-kJI3KqBSD9QjoOWYGXeNfZf" },
      { title: "Avião A400M Atlas", sub: "Airbus A400M",
        img: "1dBk8f0eWs6TWE00yvw9mj6FZ-y9_oTVd", zip: "14HQ9oLK-mriCGYzrfzeDe9XRIL6bWsmf" },
      { title: "Avião Asa Delta", sub: "Planador de asa delta",
        img: "1J7js_0dqmHuG4Kf6EcC9Gc9ec4DBUBxz", zip: "1A2t0L7skJ0KE3cylLsX4C0iIgJbNoqv0" },
      { title: "Avião F-14 TOMCAT", sub: "Caça F-14",
        img: "1OVM9sNcONvOUAIQOGJqFNDPxEEXp3Voj", zip: "1-RV1sht_Cup4r5rO7gX2-sfiQYXTIV9T" },
      { title: "Avião F-22 Raptor", sub: "Caça F-22",
        img: "1z8RAgq4iW3Oo3E35WNa8Kc6HDKv_Hcgu", zip: "1EP_T-39yg92MQdHuxrRJKfGaKf7Rsd2w" },
      { title: "Avião F4U Corsair", sub: "Caça F4U Corsair",
        img: "1Hbha-czZ5hAI65VHgNxvwJ9YrwjEkAy3", zip: "1E_Uq5nDTUKXWGXGLP2w6tHZRztj7Bz2r" },
      { title: "Avião Leve", sub: "Planador leve",
        img: "1frEw_ijx3dIoWoqxuoiUE_V3JG39XCpd", zip: "1oDcEjy4hThHM7ilPKuGBFC0iVRlwDJMH", label: "Baixar STL" },
      { title: "Avião SR-71", sub: "Avião espião SR-71",
        img: "1kboXnESg_b7lluX1YfNLIUarXiLoD2lG", zip: "13Z6ExiBnStujtKyNe9gElS6pn7Xljazf" },
      { title: "Boeing 747SP", sub: "Boeing 747",
        img: "1gOs0l0qafTzsMqBRFsIjBwqlLWZC6_q_", zip: "1xfN4wr0xA1N_8YXigwjQtp9C7DdQdOf8" },
      { title: "Cessna 152", sub: "Avião monomotor",
        img: "1KOtivRfRenK7NHg_3Yyuj6GX4T7QdkRS", zip: "1jEL6Q-fXd4J3led1LImYYSf2gwOztKbw" },
      { title: "EASYMAX", sub: "Asa de treino",
        img: "", zip: "1tfZbuSbnLzYVb0cbxyCq5m--iaSQJzLh" },
      { title: "EASYMAX FPV", sub: "Kit conversão FPV",
        img: "", zip: "1_ph-yJ7y91QhVs3_dtVdxtLqDnScpNFq" },
      { title: "EBW-160 UAV", sub: "Drone asa voadora",
        img: "1PVPXMmkAy2PyY63YKFslq1p76F4o4pgA", zip: "109dnpdOI2fXqJhsYThW0gPET-h0LB1VS" },
      { title: "Eclipson - Model V", sub: "Asa voadora",
        img: "1-AduPPp4IOnbKYvjipcKHha8anhwlOvQ", zip: "1vE_Pe0rB3kOyimakyhWaB9jQTXgiXbG0" },
      { title: "Electronoobs Spitfire", sub: "Spitfire",
        img: "1XC9_V2ON2C7V8mPpgwLEwXQTeyH6LajJ", zip: "10YTiU6UzKKk6xh38-M-INWDu5UdI5zvI" },
      { title: "Extra 300", sub: "Acrobático",
        img: "1r-fkQfWvqW90tSriMqUNuZM_JN050vOH", zip: "1j2lS9ioh_Pd1XbFFnVLUoYDhVmvQ3Hh0" },
      { title: "F-35 Lightning II", sub: "Caça F-35",
        img: "1ynCg1COyM2rOQZBkvCOdiemMFhUIwVip", zip: "1Wu-PkFsanHYnoxS5qU_orFaZ3Z9WIxs2" },
      { title: "F-86 Sabre", sub: "Caça F-86",
        img: "1Er2WEjSaheCAWmOmZw0gMkNbChSvO8R8", zip: "18KqI-ZtMZS6acdM_pgAgW35jUrnqWDdM" },
      { title: "FA-18", sub: "Caça F/A-18",
        img: "1i9gzqym_F5aIq51V3jm6n85vJxG-FcgG", zip: "1uKfpRJbDTgmbDFqoCJkqPesfMkxk7ZML" },
      { title: "Helicóptero AH-64 Apache", sub: "Helicóptero de ataque",
        img: "1bRMG3YvHTwhy52BwxgV7veCKfIWPngQ9", zip: "1Sn8uYIYJHxI3zCDeKquA4Hn3Vd6VMZvm" },
      { title: "Airwolf (CGtrader)", sub: "Bell 222 réplica",
        img: "18AK-uyKwNIpUoldacdCDg8o0P8G8wg1f", zip: "19KEqiWg5hSIEoCKLYkAF7FcLTvzlQKcJ" },
      { title: "Kraga Kodo", sub: "Aeromodelo",
        img: "1F8kG_OlT-lSHFRWLRTRCcQMa_JGGdxjc", zip: "1dRPMaJVqX5t9t6juYsdyOLtpEtQiy2kq" },
      { title: "Kraga Maripi", sub: "Aeromodelo",
        img: "1Z9pRnvAGfb-KyR3s5VDUUpDA2sQ2p9kT", zip: "1F7UR8bUR2E_bBLpFKTnmcf9QN6hxoska" },
      { title: "Kyosho Christen Eagle II", sub: "Acrobático",
        img: "1wxBPzCCLmMHhkfSAF_NCr905CvrKL0Kg", zip: "17Os1YZArpOVL5fgvtjnp00JLjBLvfSN7" },
      { title: "Messerschmitt BF 109", sub: "Caça alemão",
        img: "1L6_A6aTmxNIwrbDfVmx3N32KoyhCzqJK", zip: "1gsYUVcJ-NvvHImHhphly8qAaf2UzR1s9" },
      { title: "Messerschmitt BF 109T", sub: "Caça alemão",
        img: "1AmGe6j4KorZoH7blVzal02kKtciUrDRL", zip: "1ugypSnourpYH53ZVAzNIapHf62pHoyja" },
      { title: "MIG-15", sub: "Caça soviético",
        img: "1G9nrSzLBKeEAHqUqSC0N4b_6v4eoImpr", zip: "1CRW4vaBLLp2vt0wJwFvLiIvqj8Cri5ah" },
      { title: "P38", sub: "Caça P-38 Lightning",
        img: "10NpJOgiN9hXNe7Ut2ghsbumfY7VrnTZ6", zip: "1gimhDsm0Cu_Nxk8J-zc43q9tseGmu5GO" },
      { title: "P47 N-15 Thunderbolt", sub: "Caça P-47",
        img: "1M6JMcq8u_zmiIhgA_qh_qiNA0evolrc0", zip: "1lECGQOg5ffoPDDtxCpn--9Ccyx4RmIRN" },
      { title: "P51-D Mustang RC", sub: "Caça P-51",
        img: "1JknfLZGaXgVZGlFfAGMH_qX1H_vPuNEx", zip: "1kecJ3kvrEX1N5a5i-3K3a5F9N_p25JJi" },
      { title: "P51-D Mustang", sub: "Caça P-51",
        img: "1LnAmczv-FIybYPVEQZLQoctAWpt59aIr", zip: "1u_LtEr_I1jsoTuNLOCON3yNewV4wIKqY" },
      { title: "Piper Pawnee", sub: "Agrícola",
        img: "1bFI6IPyiyrRG9jZT6W0XAESTvI_lFjgd", zip: "16Wy3F_b6bDB3WHwwrsuE76v0omt5Up0m" },
      { title: "Qtrainer (3DLabPrint)", sub: "Treino",
        img: "1OyiNTdPW9-9rnh14KOkzo_2RrEin4Vo7", zip: "1TOS9VbWWOyeBrMIHorP1TmW7W9Y_j-Ow" },
      { title: "Qtrainer", sub: "Treino",
        img: "112Ft4D1ZynRRFahQHNgoCB-n3ZAGY1bf", zip: "1xXZClvts2ut-Be2Naqk8xHgzRIQgtPJU" },
      { title: "Siyahkanat Racing", sub: "Avião de corrida",
        img: "1Sme_qONqF2yStYMD-sHLEs22fL34Mi4H", zip: "1hUKKI4JPCXgymRf2HcOMhqq3GTyLBs0L" },
      { title: "Spitfire", sub: "Caça britânico",
        img: "", zip: "1FrBqSrtk35cGDxIkkTadOvJhRJTNezK4" },
      { title: "Stearman PT-17 Kaydet", sub: "Biplano de treino",
        img: "1m0F_D3j47HCPxVse4ndoyFeFCrxnfg-Z", zip: "1Qzv7cpsocv0MDNGlCyi1P6_fjGFp08Mz" },
      { title: "Supermarine Spitfire MkIX 2", sub: "Caça britânico",
        img: "", zip: "1bhtYPnVSy8Zpqf9P2teZGppvpJxI8n1f" },
      { title: "Supermarine Spitfire MkIX", sub: "Caça britânico",
        img: "1w-0eRcYRGzDsNP4n4oEgc6a-BloopNH-", zip: "1S_Itc6TuMNgEV1-EIjE_4ysAuMQHoyzR" },
      { title: "YAK-55", sub: "Acrobático",
        img: "1ONeZbLYmx12ywaeAs5_z8GCq4r2Qk83K", zip: "1X5X2J6u8K_mxdPkPZMFtjJn2zi7QgE-l" },
      { title: "Zivko Edge Hannes Arch", sub: "Acrobático",
        img: "1QR2tLvRvwfWmi3PYUxUcVkvGO1ysbmMy", zip: "1AsQB580J0Dz-0Q_9Br8Soqw7jCSiEYe9" }
    ]
  },
